[libraries]
work.files = [
    'vhlib/*/*.vhd',
    'vhlib/*/*/*.vhd',
    'component/*.vhd',
    'test/*.vhd',
    'test/*/*.vhd',
    'test/*/*/*.vhd',
    'test/*/*/*/*.vhd',
    'test/*/*/*/*/*.vhd',
]