name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:

  vhdl:
      name: VHDL
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ghdl/setup-ghdl-ci@master
        with:
          backend: llvm
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install vhdeps
      - name: vhdeps
        run: vhdeps -i vhlib -i component -i test ghdl -- --pattern '*_tc' --pattern ':!*/vhlib/*'